const data = [
    {
        "id": "1",
        "nombre": "titulo 1",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro1.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "2",
        "nombre": "titulo 2",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro2.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "3",
        "nombre": "titulo 3",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro3.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "4",
        "nombre": "titulo 4",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro4.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "5",
        "nombre": "titulo 5",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro5.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "6",
        "nombre": "titulo 6",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro1.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "7",
        "nombre": "titulo 7",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro2.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "8",
        "nombre": "titulo 8",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro3.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "9",
        "nombre": "titulo 9",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro4.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    },
    {
        "id": "10",
        "nombre": "titulo 10",
        "autor": "autor",
        "precio": "2000",
        "imgUrl": "libro5.jpg",
        "editorial": "LOREM",
        "coleccion": "sin coleccion",
        "idioma": "Español",
        "numeropaginas": "100",
        "dimensiones": "200cm x 125cm",
        "fechapub": "2022",
        "materia": "Cine y tv"
    }
]
export default data